sudo: required
dist: trusty
env:
  global:
    - DISPLAY=":99.0"
notifications:
  email:
    recipients:
      - ruby-gnome2-cvs@lists.sourceforge.net
rvm:
  - 2.1
  - 2.2
  - 2.3.0
  - ruby-head
matrix:
  # allow_failures:
  #   - rvm: 2.1
  fast_finish: true
before_install:
  - gem install bundler
  - sudo apt-get install -y gir1.2-clutter-1.0
before_script:
  - ./travis-before-script.sh
  - sh -e /etc/init.d/xvfb start
script:
  - bundle exec ruby extconf.rb
  - bundle exec make -j3 > /dev/null
  - bundle exec ruby run-test.rb
after_script:
  - sh -e /ext/init.d/xvfb stop
