env:
  global:
    - DISPLAY=":99.0"
notifications:
  email:
    recipients:
      - ruby-gnome2-cvs@lists.sourceforge.net
rvm:
  - 2.0.0
  - 2.1
  - 2.2
  - ruby-head
matrix:
  allow_failures:
    - rvm: 2.1
  fast_finish: true
before_script:
  - ./travis-before-script.sh
  - sh -e /etc/init.d/xvfb start
script:
  - bundle exec ruby extconf.rb
  - bundle exec make -j3 > /dev/null
  - bundle exec ruby run-test.rb
after_script:
  - sh -e /ext/init.d/xvfb stop
