env:
  global:
    - DISPLAY=":99.0"
notifications:
  recipients:
    - kou@cozmixng.org
    - myokoym@gmail.com
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.0
matrix:
  allow_failures:
    - rvm: 1.8.7
    - rvm: 2.1.0
before_script:
  - ./travis-before-script.sh
  - sh -e /etc/init.d/xvfb start
after_script:
  - sh -e /ext/init.d/xvfb stop
