env:
  global:
    - DISPLAY=":99.0"
notifications:
  recipients:
    - ruby-gnome2-cvs@lists.sourceforge.net
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
#  - ruby-head
before_script:
  - ./travis-before-script.sh
  - sh -e /etc/init.d/xvfb start
after_script:
  - sh -e /ext/init.d/xvfb stop
