notifications:
  webhooks:
    - https://webhook.commit-email.info/

services:
  - docker

matrix:
  include:
    - name: Ruby 2.4
      env: TYPE=ruby-2.4
    - name: Ruby 2.5
      env: TYPE=ruby-2.5
    - name: Ruby 2.6
      env: TYPE=ruby-2.6
    - name: Ubuntu 16.04
      env: TYPE=ubuntu-16.04
    - name: Ubuntu 18.04
      env: TYPE=ubuntu-18.04
    - name: CentOS 6
      env: TYPE=centos-6
    - name: CentOS 7
      env: TYPE=centos-7
    - name: macOS
      os: osx
      rvm: 2.6
      install:
        - bundle install
      script:
        - bundle exec rake build
        # TODO: Run tests

install:
  - docker build
      -t ruby-gnome/ruby-gnome-${TYPE}
      -f travis/Dockerfile.${TYPE}
      .

script:
  - docker run
      --interactive
      --tty
      ruby-gnome/ruby-gnome-${TYPE}
