env:
  global:
    - DISPLAY=":99.0"
notifications:
  recipients:
    - kou@cozmixng.org
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
before_script:
  - sudo apt-get install -qq -y libgirepository1.0-dev
  - sh -e /etc/init.d/xvfb start
after_script:
  - sh -e /ext/init.d/xvfb stop
