notifications:
  email:
    recipients:
      - ruby-gnome2-cvs@lists.sourceforge.net

dist: trusty

sudo: required

services:
  - docker

matrix:
  include:
    - env: TYPE=ruby-2.1
    - env: TYPE=ruby-2.2
    - env: TYPE=ruby-2.3
    - env: TYPE=ruby-2.4
    - env: TYPE=ubuntu-14.04
    - env: TYPE=ubuntu-16.04
    - env: TYPE=ubuntu-17.10
    - env: TYPE=centos-6
    - env: TYPE=centos-7
    - env: TYPE=gtk+4
    - os: osx
      rvm: 2.2
      install:
        - brew update
        - bundle install
      script:
        - rake
  allow_failures:
  #   - env: TYPE=centos-6
  #   - env: TYPE=centos-7
    - env: TYPE=gtk+4
    - os: osx
      rvm: 2.2
      install:
        - brew update
        - bundle install
      script:
        - rake

install:
  - docker build
      -t ruby-gnome2/ruby-gnome2-${TYPE}
      -f travis/Dockerfile.${TYPE}
      .

script:
  - docker run
      --interactive
      --tty
      ruby-gnome2/ruby-gnome2-${TYPE}
