notifications:
  email:
    recipients:
      - ruby-gnome2-cvs@lists.sourceforge.net

dist: trusty

sudo: required

services:
  - docker

matrix:
  include:
    - env: TYPE=ruby-2.1
    - env: TYPE=ruby-2.2
    - env: TYPE=ruby-2.3
    - env: TYPE=ruby-2.4
    # - env: TYPE=ubuntu-14.04
    # - env: TYPE=ubuntu-16.04
    - env: TYPE=ubuntu-16.10
    - env: TYPE=centos-6
    - env: TYPE=centos-7
  allow_failures:
    - env: TYPE=centos-6
    - env: TYPE=centos-7

install:
  - docker build
      -t ruby-gnome2/ruby-gnome2-${TYPE}
      -f travis/Dockerfile.${TYPE}
      .

script:
  - docker run
      --interactive
      --tty
      ruby-gnome2/ruby-gnome2-${TYPE}
      sh -c
        "xvfb-run --server-args '-screen 0 640x480x24' bundle exec rake"
